PINS = {
    "JTAGSEL" : 13,
    "TESTEN" : 21,
    "INTERRUPT" : 9,
    "TMS" : 14,
    "TDO" : 15,
    "TDI" : 18,
    "BMBSRCLK" : 22,
    "BMARCLK" : 27,
    "BMASRCLK" : 17,
    "TCK" : 4,
    "BMBRCLK" : 24,
    "SRA" : 23,
    "SRB" : 25,
    "SHUTDOWN" : 7,
    "DISPRES" : 6,
    "DISPDC" : 20,
}
